apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: teamtwohotel
  labels:
    app: gateway 
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway 