apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: 879772956301.dkr.ecr.eu-central-1.amazonaws.com/payment:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          # livenessProbe:
          #   exec:
          #     command:
          #     - cat 
          #     - /tmp/healthy
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 2
          #   periodSeconds: 10
          #   failureThreshold: 5
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
          - name: MIN_TAX_PRICE
            valueFrom:
              configMapKeyRef:
                name: calltaxi-config
                key: min_tax_price
          - name: PAYMENT_GATEWAY_SERVER
            valueFrom:
              configMapKeyRef:
                name: calltaxi-config
                key: payment_gateway_server
          volumeMounts:
          - mountPath: '/mnt/efs'
            name: myvolume
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: aws-efs